openapi: 3.0.1
info:
  title: TicketUM Event Management App - API
  description: |-
    Esta es una API de creacion de Tickets para eventos.
  termsOfService: http://swagger.io/terms/
  version: v1
servers:
  - url: http://localhost:8080
    description: TicketUM API
paths:
  /events:
    get:
      tags:
        - events
      summary: This endpoint returns the current available events
      operationId: showEvents
      responses:
        '200':
          description: Events List
          content:
            '*/*':
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Event'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'

  /events/{code}:
    get:
      tags:
        - events
      summary: This endpoint returns the specific event by an event code
      operationId: showEvent
      parameters:
        - name: code
          in: path
          required: true
          description: The event code
          schema:
            type: string
      responses:
        '200':
          description: Details of the requested event
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'

  /events/{eventCode}/inscriptions:
    post:
      tags:
        - inscriptions
      summary: This endpoint creates an inscription and add it to an event
      operationId: addInscription
      parameters:
        - name: eventCode
          in: path
          required: true
          description: The event code
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guest'
      responses:
        '200':
          description: Registration Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Inscription'
          
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
                
  /events/{eventCode}/inscriptions/{guestCode}:
    get:
      tags:
        - inscriptions
      summary: This endpoint returns a specific inscription by guest code
      operationId: showInscription
      parameters:
        - name: eventCode
          in: path
          required: true
          description: The event code stored in the inscription
          schema:
            type: string
        - name: guestCode
          in: path
          required: true
          description: The guest code stored in the inscription
          schema: 
            type: string
      responses:
        '200':
          description: Details of a Guest Inscription of an specific event
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Inscription'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - inscriptions
      summary: This endpoint deletes a guest inscription from an event
      operationId: deleteGuestInscriptionFromEvent
      parameters:
        - name: eventCode
          in: path
          required: true
          description: The event code
          schema:
            type: string
        - name: guestCode
          in: path
          required: true
          description: The guest code
          schema:
            type: string
      responses:
        '200':
          description: Registration Canceled

        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Guest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        dni:
          type: string
        
    Event:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
        date:
          type: string
        location:
          type: string
        capacity: 
          type: integer
        totalInscriptions:
          type: integer
    
    Inscription:
      type: object
      properties:
        status:
          type: string
        eventCode:
          type: string
        guestCode:
          type: string
          
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error description
      example:
        message: Bad Request