@startuml Class Diagram

class Event {
    - name: String
    - date: Date
    - location: String
    - description: String
    - attendees: List<Guests>
    + add_guest(guest: Guest)
}

class Guest {
    - name: String
    - email: String
    - phone: String
    - dni: String
}

Event "1" *-- "1..*" Guest