@startuml Class Diagram

class Event {
    - eventCode: String
    - name: String
    - date: Date
    - location: String
    - description: String
    - guests: List<Guests>
    - capacity: Int
    + addGuest(guest: Guest)
}

class Guest {
    - name: String
    - email: String
    - phone: String
    - dni: String
    - eventsList: List<Event>
}

Event "1..*" *--* "1..*" Guest